DemoApplication/ViewModels/Admin/Book/Add/AddViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace DemoApplication.ViewModels.Admin.Book.Add
{
    public class AddViewModel
    {
        public int? Id { get; set; }

        public string? Title { get; set; }

        public decimal Price { get; set; }

        [Required]
        public List<int> CategoryIds { get; set; }

        [Required]
        public int AuthorId { get; set; }


        public List<AuthorListItemViewModel>? Authors { get; set; }
        public List<CategoryListItemViewModel>? Categories { get; set; }
    }
}

DemoApplication/ViewModels/Admin/Book/Add/AuthorListItemViewModel.cs
namespace DemoApplication.ViewModels.Admin.Book.Add
{
    public class AuthorListItemViewModel
    {
        public int Id { get; set; }

        public string FullName { get; set; }

        public AuthorListItemViewModel(int id, string fullName)
        {
            Id = id;
            FullName = fullName;
            
        }
    }
}

DemoApplication/ViewModels/Admin/Book/Add/CategoryListItemViewModel.cs
namespace DemoApplication.ViewModels.Admin.Book.Add
{
    public class CategoryListItemViewModel
    {
        public int Id { get; set; }
        public string Title { get; set; }


        public CategoryListItemViewModel(int id, string title)
        {
            Id = id;
            Title = title;
        }
    }
}

DemoApplication/ViewModels/Admin/Navbar/AddViewModel.cs
using DemoApplication.Database.Models;
using DemoApplication.ViewModels.Admin.Book.Add;
using DemoApplication.ViewModels.Admin.Navbar;
using System.ComponentModel.DataAnnotations;

namespace DemoApplication.ViewModels.Admin.Navbar
{
    public class AddViewModel
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public int Row { get; set; }
        public bool IsMain { get; set; }
        public bool IsHeader { get; set; }
        public bool IsFooter { get; set; }
        public List<SubNavbar> SubNavbars { get; set; }

    }
}

DemoApplication/ViewModels/Admin/Subnavbar/AddviewModel.cs
using DemoApplication.ViewModels.Admin.Book.Add;
using DemoApplication.ViewModels.Admin.Navbar;
using System.ComponentModel.DataAnnotations;

namespace DemoApplication.ViewModels.Admin.Subnavbar
{
    public class AddviewModel
    {
        public int? Id { get; set; }

        public string? Name { get; set; }

        public string ToUrl { get; set; }

        public int NavbarId { get; set; }

        public int Row { get; set; }

        public List<NavbarListViewModel>? Navbars { get; set; }
    }
}

DemoApplication/ViewModels/Admin/Subnavbar/SubNavbarListViewModel.cs
using DemoApplication.Database.Models;
using DemoApplication.ViewModels.Admin.Navbar;

namespace DemoApplication.ViewModels.Admin.Subnavbar
{
    public class SubNavbarListViewModel
    {
        public int Id { get; set; }
        public string Navbar { get; set; }
        public string Name { get; set; }
        public string ToUrl { get; set; }
        public int Row { get; set; }

        public NavbarListViewModel NavbarListViewModel { get; set; }



        public SubNavbarListViewModel(int id,string navbar, string name, string toUrl, int row)
        {
            Id = id;
            Navbar = navbar;
            Name = name;
            ToUrl = toUrl;
            Row = row;
        }
    }
}

DemoApplication/ViewModels/Client/Book/AddViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace DemoApplication.ViewModels.Client.Book
{
    public class AddViewModel : BaseViewModel
    {

    }
}

DemoApplication/ViewModels/Client/Book/Update/UpdateRequestViewModel .cs
using System.ComponentModel.DataAnnotations;

namespace DemoApplication.ViewModels.Client.Book.Update
{
    public class UpdateRequestViewModel : BaseViewModel
    {

    }
}

DemoApplication/ViewModels/Client/Book/Update/UpdateResponseViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace DemoApplication.ViewModels.Client.Book.Update
{
    public class UpdateResponseViewModel : BaseViewModel
    {
        public int Id { get; set; }
    }
}

DemoApplication/Controllers/Admin/SubNavbarController.cs
using DemoApplication.Database;
using DemoApplication.Database.Models;

using DemoApplication.ViewModels.Admin.Navbar;
using DemoApplication.ViewModels.Admin.Subnavbar;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Xml.Linq;

namespace DemoApplication.Controllers.Admin
{
    [Route("Subnavbar")]
    public class SubNavbarController : Controller
    {
        private readonly DataContext _dataContext;
        public SubNavbarController(DataContext dataContext)
        {
            _dataContext = dataContext;
        }

        [HttpGet("list", Name = "Subnavbar-list")]
        public IActionResult List()

        {
            var model = _dataContext.SubNavbars.Select(s => new SubNavbarListViewModel(s.Id, s.Navbar.Name, s.Name, s.ToUrl, s.Row)).ToList();

            return View("~/Views/Admin/Subnavbar/List.cshtml", model);
        }

        #region Add

        [HttpGet("add", Name = "subnavbar-add")]
        public IActionResult Add()
        {
            var model = new ViewModels.Admin.Subnavbar.AddviewModel
            {
                Navbars = _dataContext.Navbars
                    .Select(n => new NavbarListViewModel(n.Id, n.Name, n.IsMain, n.IsHeader, n.IsFooter,n.Row))
                    .ToList(),
            };

            return View("~/Views/Admin/Subnavbar/Add.cshtml", model);
        }



        [HttpPost("add", Name = "subnavbar-add")]
        public IActionResult Add(ViewModels.Admin.Subnavbar.AddviewModel model)
        {
            if (!ModelState.IsValid)
            {
                return GetView(model);
            }

            if (!_dataContext.Navbars.Any(a => a.Id == model.NavbarId))
            {
                ModelState.AddModelError(String.Empty, "Navbar is not found");
                return GetView(model);
            }




            AddSubNavbar();

            return RedirectToRoute("Subnavbar-list");




            IActionResult GetView(ViewModels.Admin.Subnavbar.AddviewModel model)
            {
                model.Navbars = _dataContext.Navbars
                    .Select(n => new NavbarListViewModel(n.Id, n.Name, n.IsMain, n.IsHeader, n.IsFooter,n.Row))
                    .ToList();



                return View("~/Views/Admin/Subnavbar/Add.cshtml", model);
            }

            void AddSubNavbar()
            {
                var subnavbar = new SubNavbar
                {

                    Name = model.Name,
                    NavbarId = model.NavbarId,
                    ToUrl = model.ToUrl,
                    Row = model.Row
                };

                _dataContext.SubNavbars.Add(subnavbar);



                _dataContext.SaveChanges();
            }
        }


        #endregion

        #region Update

        [HttpGet("update/{id}", Name = "subnavbar-update")]
        public async Task<IActionResult> UpdateAsync([FromRoute] int id)
        {
            var subnavbar = await _dataContext.SubNavbars.FirstOrDefaultAsync(b => b.Id == id);
            if (subnavbar is null)
            {
                return NotFound();
            }

            var model = new AddviewModel
            {
                Id = subnavbar.Id,
                Name = subnavbar.Name,
                ToUrl = subnavbar.ToUrl,
                NavbarId = subnavbar.NavbarId,
                Row = subnavbar.Row,
                Navbars =
                    _dataContext.Navbars
                        .Select(n => new NavbarListViewModel(n.Id, n.Name, n.IsMain, n.IsHeader, n.IsFooter, n.Row)).ToList()
            };

            return View("~/Views/Admin/Subnavbar/Update.cshtml", model);
        }

        [HttpPost("update/{id}", Name = "subnavbar-update")]
        public async Task<IActionResult> UpdateAsync(AddviewModel model)
        {
            var subnavbar = await _dataContext.SubNavbars.FirstOrDefaultAsync(b => b.Id == model.Id);
            if (subnavbar is null)
            {
                return NotFound();
            }

            if (!ModelState.IsValid)
            {
                return GetView(model);
            }

            if (!_dataContext.Navbars.Any(a => a.Id == model.NavbarId))
            {
                ModelState.AddModelError(String.Empty, "Navbar is not found");
                return GetView(model);
            }



            UpdateSubNavbarAsync();

            return RedirectToRoute("subnavbar-list");

            IActionResult GetView(AddviewModel model)
            {
                model.Navbars = _dataContext.Navbars
                    .Select(n => new NavbarListViewModel(n.Id, n.Name, n.IsMain, n.IsHeader, n.IsFooter, n.Row))
                    .ToList();



                return View("~/Views/Admin/Subnavbar/Add.cshtml", model);
            }

            async Task UpdateSubNavbarAsync()
            {
                subnavbar.Name = model.Name;
                subnavbar.NavbarId = model.NavbarId;
                subnavbar.ToUrl = model.ToUrl;
                subnavbar.Row = model.Row;

                _dataContext.SubNavbars.Add(subnavbar);

                _dataContext.SaveChanges();
            }
        }

        #endregion

        #region Delete

        [HttpPost("delete/{id}", Name = "subnavbar-delete")]
        public async Task<IActionResult> DeleteAsync([FromRoute] int id)
        {
            var subnavbar = await _dataContext.SubNavbars.FirstOrDefaultAsync(b => b.Id == id);
            if (subnavbar is null)
            {
                return NotFound();
            }

            _dataContext.SubNavbars.Remove(subnavbar);
            await _dataContext.SaveChangesAsync();

            return RedirectToRoute("subnavbar-list");
        }

        #endregion
    }
}

DemoApplication/Views/Admin/Subnavbar/Add.cshtml
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@using DemoApplication.ViewModels.Admin.Subnavbar
@model AddviewModel

<div class="row">
    <div class="col-lg-12">
        <div class="card">
            <div class="card-header">
                <h4 class="card-title">Subnavbars</h4>
            </div>
            <div class="card-body">
                <div class="general-label">
                    <form method="POST" asp-route="subnavbar-add">
                        <div class="text-danger" asp-validation-summary="ModelOnly"></div>


                        <div class="form-group">
                            <label>Navbars</label>
                            <select asp-for="NavbarId" asp-items="@(new SelectList(Model.Navbars, nameof(SubNavbarListViewModel.Id), nameof(SubNavbarListViewModel.Name)))" class="form-select">                            </select>
                            <span asp-validation-for="NavbarId" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label>Name</label>
                            <input asp-for="Name" class="form-control">
                            <span asp-validation-for="Name" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label>ToUrl</label>
                            <input asp-for="ToUrl" class="form-control">
                            <span asp-validation-for="ToUrl" class="text-danger"></span>
                        </div>


                        <button type="submit" class="btn btn-primary">Submit</button>
                    </form>
                </div>
            </div><!--end card-body-->
        </div><!--end card-->
    </div>
</div>

DemoApplication/Views/Admin/Subnavbar/List.cshtml
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@using DemoApplication.ViewModels.Admin.Subnavbar
@model List<SubNavbarListViewModel>

<div class="col-lg-12">
    <div class="row justify-content-end">
        <div class="">
            <a asp-controller="Navbar" asp-action="add" target="_blank" class="btn btn-secondary">Add new Navbar</a>
        </div>
        <div class="">
            <a asp-controller="SubNavbar" asp-action="add" target="_blank" class="btn btn-secondary">Add new Subnavbar</a>
        </div>
    </div>
</div>
<div class="col-lg-12">
    <div class="card">
        <div class="card-header">
            <h4 class="card-title">Books</h4>
        </div><!--end card-header-->
        <div class="card-body">
            <div class="table-responsive">
                <table class="table table-striped mb-0">
                    <thead>
                        <tr>
                            <th>Navbar</th>
                            <th>SubNavbar</th>
                            <th class="text-end">Actions</th>

                        </tr>
                    </thead>
                    <tbody>
  
                        @foreach (var subnavbar in Model)
                        {
                            <tr>
                                <td>@subnavbar.Navbar</td>
                                <td>@subnavbar.Name</td>
                                <td class="text-end">
                                     <a asp-route="subnavbar-update" asp-route-id="@subnavbar.Id"><i class="las la-pen text-secondary font-16"></i></a>
                                     <form method="POST" asp-route="subnavbar-delete" asp-route-id="@subnavbar.Id" id="subnavbar-form-@subnavbar.Id" ></form>
                                     <button type="submit" form="subnavbar-form-@subnavbar.Id">
                                        <i class="las la-trash-alt text-secondary font-16"></i>
                                    </button>
                                </td>
                            </tr>    
                        }
                    </tbody>
                </table><!--end /table-->
            </div><!--end /tableresponsive-->
        </div><!--end card-body-->
    </div><!--end card-->
</div>

DemoApplication/Views/Admin/Subnavbar/Update.cshtml
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@using DemoApplication.ViewModels.Admin.Subnavbar
@using DemoApplication.ViewModels.Admin.Navbar
@model AddviewModel
<div class="row">
    <div class="col-lg-12">
        <div class="card">
            <div class="card-header">
                <h4 class="card-title">Subnavbars</h4>
            </div>
            <div class="card-body">
                <div class="general-label">
                    <form method="POST" asp-controller="Subnavbar" asp-action="update" asp-route-id="@Model.Id" >
                        <div class="text-danger" asp-validation-summary="ModelOnly"></div>
                        

                        <div class="form-group">
                            <label>Navbars</label>
                            <select asp-for="NavbarId" asp-items="@(new SelectList(Model.Navbars, nameof(NavbarListViewModel.Id), nameof(NavbarListViewModel.Name)))" class="form-select">                            </select>
                            <span asp-validation-for="NavbarId" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label>Name</label>
                            <input asp-for="Name" class="form-control">
                            <span asp-validation-for="Name" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label>ToUrl</label>
                            <input asp-for="ToUrl" class="form-control">
                            <span asp-validation-for="ToUrl" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label>Row</label>
                            <input asp-for="Row" class="form-control">
                            <span asp-validation-for="Row" class="text-danger"></span>
                        </div>

                        <button type="submit" class="btn btn-primary">Submit</button>
                    </form>
                </div>
            </div><!--end card-body-->
        </div><!--end card-->
    </div>
</div>